routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/fields', 'FieldsController'); 
Route::resource('/field/{field_id}/products', 'ProductsController'); 

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
  return redirect('fields');
});

app/Field.php
<?php

namespace App;

use Auth;
use App\Product;

use Illuminate\Database\Eloquent\Model;

class Field extends Model
{
    protected $fillable = [
        'name'
    ];

    public function products()
    {
        return $this->belongsToMany('App\Product');
    }
}

app/Product.php
<?php

namespace App;

use Auth;
use App\Field;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'quantity'
    ];

    public function fields()
    {
        return $this->belongsToMany('App\Field');
    }
}

app/User.php
<?php

namespace App;

use App\Field;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function fields()
    {
        return $this->hasMany('App\Field')->orderBy('created_at', 'DESC');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FieldsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Field;
use App\Product;

use Illuminate\Http\Request;

class FieldsController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }

    public function index() {

    	$user = auth()->user();
    	$fields = $user->fields;

    	return view('fields.index', compact('user', 'fields'));
    }

    public function create() {

    	return view('fields.create');
    }

    public function store(Request $request)  
    {

        $field = new Field($request->all());
        $field->user_id = auth()->user()->id;

        $field->save();

        return redirect('fields');
    
    }

    public function edit($id) 
    {

        $field = Field::find($id);
        
        return view('fields.edit', compact('field'));
    }

    public function update($id, Request $request) 
    {

        $field = Field::find($id);
        $field->update($request->all());

        return redirect('fields');
    }

    public function destroy($id) 
    {
        $field = Field::find($id);
        $field->delete();
        
        return redirect('fields');
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Field;
use App\Product;

use Illuminate\Http\Request;

class ProductsController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($field_id, Request $request) {

        $field = Field::find($field_id);
        $products = $field->products;

    	return view('products.index', compact('field', 'products'));
    }

    public function create($field_id, Request $request) {

        $field = Field::find($field_id);

    	return view('products.create', compact('field'));
    }

    public function store($field_id, Request $request)  
    {

        $product = new Product($request->all());
        $product->save();

        $product->fields()->attach($field_id);

        return redirect('fields');
    
    }

    public function edit($field_id, $id) 
    {

        $product = Product::find($id);
        $field = Field::find($field_id);

        return view('products.edit', compact('product', 'field'));
    }

    public function update($field_id, $id, Request $request) 
    {

        $product = Product::find($id);
        $product->update($request->all());

        return redirect('fields');
    }

    public function destroy($field_id, $id) 
    {
        $product = Product::find($id);
        $product->delete();
        
        return redirect('fields');
    }
}

resources/views/fields/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">

		<h1>New Field</h1>
		<hr>

			{!! Form::open(['url' => 'fields']) !!}
				
				@include('fields.form', ['submitButtonText' => 'Add'])
				
			{!! Form::close() !!}

	</div>
	
@stop

resources/views/fields/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">

		<h1>Editing: {!! $field->name !!}</h1>
		<hr>

			{!! Form::model($field, ['method' => 'PATCH', 'action' => ['FieldsController@update', $field->id]]) !!}
				
				@include('fields.form', ['submitButtonText' => 'Save changes'])

			{!! Form::close() !!}

	</div>

@stop

resources/views/fields/form.blade.php
	<div class="form-group">

		{!! Form::label('name', 'Name:') !!}
		{!! Form::text('name', null, ['class' => 'form-control']) !!}

	</div>		

	<div class="form-group">
	
		{!! Form::submit($submitButtonText, ['class' => 'btn btn-primary form-control']) !!}
	
	</div>

resources/views/fields/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">

			<div class="col-lg-8">
				<h1>Fields</h1>
			</div>

			<div class="col-lg-4">
				<a class="btn btn-success" href="{{ url('/fields/create') }}">Add field</a>
			</div>
			<hr>

			<table class="table">
				<thead>
					<th>id</th>
					<th width="300px">name</th>
					<th>Products amount</th>
					<th>Products</th>
					<th>Manage</th>
					<th></th>
				</thead>
				<tbody>

					@foreach($fields as $field)
						<tr>
							<td>{{ $field->id }}</td>
							<td>{{ $field->name }}</td>
							<td>{{ count($field->products) }}</td>
							<td>
								@foreach($field->products as $product)
									{{ $product->name }} ({{ $product->quantity }})<br>
								@endforeach
							</td>
							<td>
								<a class="btn-primary btn-sm" href="{{ route('products.index', [$field->id]) }}">Manage products</a>
							</td>
							<td>
								<a class="btn-primary btn-sm" href="{{ route('fields.edit', [$field->id]) }}">Edit</a>

								<form action="{{ route('fields.destroy', [$field->id]) }}" method="POST">
									@method('DELETE')
 									@csrf
 									<button type="submit" class="btn-danger btn-sm">Delete</button>  
								</form>
							</td>
						</tr>
					@endforeach

				</tbody>
			</table>	

			
		</div>
	</div>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/bootstrap.min.js') }}?t=<?php echo(microtime(true)); ?>"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap.min.css') }}?t=<?php echo(microtime(true)); ?>" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">

		<h1>New Product</h1>
		<hr>

			{{ Form::open(array('route' => array('products.store', $field->id), 'class' => 'section-top')) }}
				
				@include('products.form', ['submitButtonText' => 'Add'])
				
			{!! Form::close() !!}

	</div>
	
@stop

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">

		<h1>Editing: {!! $product->name !!}</h1>
		<hr>


			{!! Form::model($product, ['method' => 'PATCH', 'action' => ['ProductsController@update', $field->id, $product->id]]) !!}
				
				@include('products.form', ['submitButtonText' => 'Save changes'])

			{!! Form::close() !!}

	</div>

@stop

resources/views/products/form.blade.php
	<div class="form-group">

		{!! Form::label('name', 'Name:') !!}
		{!! Form::text('name', null, ['class' => 'form-control']) !!}

	</div>		

	<div class="form-group">

		{!! Form::label('quantity', 'Quantity:') !!}
		{!! Form::number('quantity', null, ['class' => 'form-control']) !!}

	</div>

	<div class="form-group">
	
		{!! Form::submit($submitButtonText, ['class' => 'btn btn-primary form-control']) !!}
	
	</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">

			<div class="col-lg-8">
				<h1>Products of {{ $field->name }}</h1>
			</div>

			<div class="col-lg-4">
				<a class="btn btn-success" href="{{ route('products.create', ['field_id' => $field->id]) }}">Add product</a>
			</div>

			<hr>

			<table class="table">
				<thead>
					<th>id</th>
					<th width="300px">name</th>
					<th>Quantity</th>
					<th></th>
				</thead>
				<tbody>

					@foreach($products as $product)
						<tr>
							<td>{{ $product->id }}</td>
							<td>{{ $product->name }}</td>
							<td>{{ $product->quantity }}</td>
							<td>
								<a class="btn-primary btn-sm" href="{{ route('products.edit', ['field_id' => $field->id, 'product' => $product->id]) }}">Edit</a>

								<form action="{{ route('products.destroy', ['field_id' => $field->id, 'product' => $product->id]) }}" method="POST">
									@method('DELETE')
 									@csrf
 									<button type="submit" class="btn-danger btn-sm">Delete</button>  
								</form>
							</td>
						</tr>
					@endforeach

				</tbody>
			</table>	

			
		</div>
	</div>
@stop